"fixing pipeline"

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -8,6 +8,10 @@ if [ "$branch" = "main" ]; then
   exit 1
 fi
 
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
 
 npm run lint
 npm run test
