added block for commits to master/main

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+if [ "$branch" = "master" or "$branch" = "main"]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
+
 npm run lint
 npm run test
+
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
